# render.yaml - Configuration pour déployer Keycloak sur Render

services:
  - type: web
    name: Keycloak  # Nom de votre service (modifiable)
    runtime: docker
    plan: free      # Ou "standard" pour la production
    region: frankfurt  # Doit correspondre à la région de votre DB
    env: docker
    healthCheckPath: /health
    dockerfilePath: Dockerfile  # Chez vers votre Dockerfile

    # Configuration cruciale du port
    port: 8080  # Keycloak écoute par défaut sur le port 8080
    
    # Variables d'environnement critiques
    envVars:
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL
        value: jdbc:postgresql://dpg-cvuebl15pdvs73c27440-a:5432/pca_pay_db
      - key: KC_DB_USERNAME
        value: admin
      - key: KC_DB_PASSWORD
        sync: false  # À définir manuellement dans le dashboard Render
      
      # Configuration HTTPS/Proxy (nécessaire pour Render)
      - key: KC_PROXY
        value: edge
      - key: KC_HOSTNAME_STRICT
        value: "false"
      - key: KC_HTTP_ENABLED
        value: "true"
      
      # Admin credentials (à sécuriser)
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false  # À définir manuellement
      
      # Optimisations
      - key: KC_HEALTH_ENABLED
        value: "true"
      - key: KC_METRICS_ENABLED
        value: "true"

    # Ressources (ajuster pour la production)
    resources:
      memoryMB: 512  # Minimum recommandé pour Keycloak
      cpuShares: 1000

network:
      servicePort: 8080  # Renforce la configuration du port
# Pas besoin de section 'databases' car vous utilisez pca-pay-db existante
