services:
  - type: web
    name: keycloak-service  # Choisissez un nom
    runtime: docker
    plan: free
    env: docker
    envVars:
      - key: KC_DB_URL
        value: jdbc:postgresql://dpg-cvuebl15pdvs73c27440-a:5432/pca_pay_db
      - key: KC_DB_USERNAME
        value: admin
      - key: KC_DB_PASSWORD
        sync: false  # Important pour les secrets!
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
    healthCheckPath: /health
